landscapeMemberClasses:
   - name: Platinum Membership
     category: Platinum
   - name: Gold Membership
     category: Gold
   - name: Silver Membership
     category: Silver
   - name: Silver Membership - MPSF
     category: Silver
   - name: Associate Membership
     category: Associate
project: a0941000002wBz9AAE # The Linux Foundation
memberSuffix: " (member)"
memberUsePublicMembershipLogo: true
slug: tlf
landscapeMemberCategory: LF Members
landscapeProjectsCategory: Projects
landscapeProjectsSubcategories:
  - name: All
    category: All
landscapefile: landscape.yml
projectsDefaultCrunchbase: https://www.crunchbase.com/organization/linux-foundation
projectsAddTechnologySector: true
projectsAddIndustrySector: true
projectsAddPMOManagedStatus: true
projectsAddParentProject: true
projectsFilterByParentSlug: false
projectsAddCategory: false
