name: Autocommit pull requests

on:
  workflow_dispatch:
  schedule: 
    - cron:  '20 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Automerge Pull Request if possible
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          MERGE_LABELS: "daily-update"
          MERGE_RETRY_SLEEP: 300000
          MERGE_METHOD: "squash"
